version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 982081073687.dkr.ecr.ap-south-1.amazonaws.com
      
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t crypto-exchange .
      - docker tag crypto-exchange:latest 982081073687.dkr.ecr.ap-south-1.amazonaws.com/crypto-exchange:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 982081073687.dkr.ecr.ap-south-1.amazonaws.com/crypto-exchange:latest
artifacts:
  files:
    - app.py
    - Dockerfile
    - requirements.txt
