version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-ecr-repository-url>
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t crypto-exchange .
      - docker tag crypto-exchange:latest <your-ecr-repository-url>:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push <your-ecr-repository-url>:latest
artifacts:
  files:
    - app.py
    - Dockerfile
    - requirements.txt
